### ISSUE TITLE
No data directory/examples from early in course

### ISSUE THREAD

**Issue by jbatchelor** [robconery/meteor-shop#3]
In the "Test Data" module, you mention dragging in some test data from js files, but those js files do not appear to be included anywhere in this project. It's a little difficult to see the same results on our pages without recreating that test data, by hand. Any chance we can get these data files included in the repo?

**Comment by robconery** [comment]
All of that data is here:
https://github.com/robconery/meteor-shop/blob/master/server/seeds.js
