### ISSUE TITLE
Total not updateing in cart

### ISSUE THREAD

**Issue by note89** [robconery/meteor-shop#7]
Hi im following you guide and im haveing some trouble. 
My global variable currentCart does not work the same as yours does.
I dont send a new currentCart to save when i update the values in the textinput in the cart

```
Template.cartShow.helpers({
    cart: function () {
        currentCart = Carts.getCart(userKey);
        return currentCart;
    },
    thereAreNo: function (items) {
        return items.length == 0;
    }
});

Template.cartShow.events({
    "click .remove-from-cart": function (ev) {
        ev.preventDefault();
        removeFromCart(this.sku, function (err, res) {
            if (err) {
                console.log(err);
            } else {
                //any items left?
                currentCart = res; //Have to save over currentCart <<<<<<<<<<<<<<<<<
                if (currentCart.items.length === 0) {
                    Router.go("homeIndex");
                }
            }
        });
    },
    "change .item-qty": function (ev) {
        var newQty = parseInt($(ev.currentTarget).val());
        var name = this.name;
        if (newQty === 0) {
            removeFromCart(this.sku)
        } else {
            this.quantity = parseInt(newQty); // does not change currentCart <<<<<<<<<<<<<
            console.log(this.quantity); // updated to new value
            console.log(currentCart); // not changed
            saveCart(currentCart, function (err, res) {
                if (err) {
                    console.log(err)
                }
                else {
                    console.log("changed data");
                    //alert(name + " updated");
                }
            });
            $(ev.currentTarget).val(newQty);
        }
    }
});
```

**Comment by robconery** [comment]
Might need a little more detail here about your problems.

**Comment by note89** [comment]
That was some fast reply. In the first example i get the feeling that the cart object that is supposed to get mutated by`removeFromCart` should be the same as `currentCart = Carts.getCart(userKey);`
and that `currentCart = res;` is the wrong approach. 

here is my repo https://github.com/Niler851/rocket-shop
and here is the website http://ventureintospace.meteor.com/

**Comment by robconery** [comment]
Can you do me a favor and tell me _what the problem is_. Right now all I know is "something's wrong". Tell me what's wrong, what you expect, a stack trace and any debugging you've done.

**Comment by note89** [comment]
currentCart does not update when i change the quantity in the text input. 
I can change the quantity as much as i like but the total remains the same and if i refresh i the quantity is back to where it started.

**Comment by robconery** [comment]
The method you want is `updateCart`:

https://github.com/robconery/meteor-shop/blob/master/client/templates/cart/show.js#L35

**Comment by note89** [comment]
Well you start off by doing saveCart in you video so i though i would start by making that work ?

**Comment by robconery** [comment]
Feel free to email me if you have any questions RE the vid. This is an issues list for the code as it is now (my email is on the video).
